# Site settings
title: Nomi Nomi - Coming Soon
email: team@nominomi.co
description: > # this means to ignore newlines until "baseurl:"
  Find Your City's Best Streetfood Chefs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nominomi.co" # the base hostname & protocol for your site
twitter_username: nomi_food
github_username:  nominomi

# Build settings
markdown: kramdown

gems: ['kramdown', 'jekyll-redirect-from', 'jekyll-sitemap']
# , 'jekyll-minifier', 'jekyll-seo-tag']

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

permalink: /community/tutorials/:title.html
